### ISSUE TITLE
NPE when Json.toJson

### ISSUE THREAD

**Issue by hepin1989** [playframework/play-json#100]
```
Caused by: java.lang.NullPointerException
	at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$2(Writes.scala:307)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$1(Writes.scala:307)
	at play.api.libs.json.Writes$$anon$6.writes(Writes.scala:142)
	at play.api.libs.json.PathWrites.$anonfun$nullable$2(JsConstraints.scala:184)
	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
	at play.api.libs.json.OWrites$MergedOWrites$.mergeIn(Writes.scala:75)
	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:67)
	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:63)
	at play.api.libs.json.OWrites$MergedOWrites$.mergeIn(Writes.scala:73)
	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:66)
	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writeFields(Writes.scala:63)
	at play.api.libs.json.OWrites$OWritesFromFields.writes(Writes.scala:95)
	at play.api.libs.json.OWrites$OWritesFromFields.writes$(Writes.scala:93)
	at play.api.libs.json.OWrites$MergedOWrites$$anon$1.writes(Writes.scala:63)
	at play.api.libs.json.OWrites$$anon$2.$anonfun$contramap$1(Writes.scala:106)
	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:111)
	at play.api.libs.json.OWrites$$anon$3.writes(Writes.scala:110)
	at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$2(Writes.scala:307)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$1(Writes.scala:307)
	at play.api.libs.json.Writes$$anon$6.writes(Writes.scala:142)
	at play.api.libs.json.Json$.toJson(Json.scala:186)
	at controllers.FacadesController.$anonfun$queryTypes$2(FacadesController.scala:28)

```

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/29998660-b76330be-9063-11e7-98b2-e41c8cc04a6e.png)

**Comment by hepin1989** [comment]
The root cause is I am using a `Recursive Types` and auto mapping, so boom! 
The automapping gave me a `Writes`, but with the recursived one as `null`.

**Comment by hepin1989** [comment]
easy fixed with  a `lazy`.

1. The macro should throw exception when auto mapping the recursive type.
2. When the `Writes` is null,throw an exception.

**Comment by cchantep** [comment]
Hi @hepin1989, the macro could check for direct reference to the same type (which anyway lead to issue in Scala), on the other side indirect reference using `Option` or `Traversable` could be supported.
